In [2]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 13, -12, -72,  28, -22,  56])

In [4]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
 zeros = torch.zeros(2, 3)
 zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.empty(2, 3)
input

tensor([[8.2240e-37, 4.5678e-41, 3.5598e-35],
        [0.0000e+00, 4.4842e-44, 0.0000e+00]])

In [8]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [9]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [10]:
logspace = torch.logspace(start=-10, end=10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [11]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [12]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[140003108449440,       104704064,               1],
        [      104700640,               0,               0]])

# CPU vs GPU performance comparision

In [13]:
import numpy as np
import time

In [14]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00014186
CPU times: user 352 µs, sys: 72 µs, total: 424 µs
Wall time: 356 µs


In [15]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()
rand = (torch_rand1 @ torch_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"GPU : {elapsed_time:.8f}")

start_time = time.time()
rand = np.multiply(np_rand1, np_rand2)
end_time = time.time()
elapsed_time = end_time - start_time
print(f"CPU : {elapsed_time:.8f}")

GPU : 0.20300460
CPU : 0.26973987


In [16]:
"""
torch.stack 
torch.multinomial
torch.tril
torch.triu
input.T / input.transpose
nn.Linear
torch.cat
F.softmax
"""

# define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor

# draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [17]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [18]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [19]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [20]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [21]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [22]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [23]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
import torch.nn as nn

sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)

print(linear(sample))

def build_nn(layout):
    network = []
    for idx in range(len(layout)):
        if idx == len(layout) - 1:
            continue

        ins, outs = layout[idx], layout[idx + 1]
        model = nn.Linear(ins, outs)
        network.append(model)
    
    return network

network = build_nn([2, 4, 3, 1])

print(network)

tensor([-5.0668, -5.0105,  2.4884], grad_fn=<SqueezeBackward4>)
[Linear(in_features=2, out_features=4, bias=True), Linear(in_features=4, out_features=3, bias=True), Linear(in_features=3, out_features=1, bias=True)]


In [25]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)



tensor([0.0900, 0.2447, 0.6652])


In [26]:
# initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

print(embedding)

# create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# apply the embedding layer
embedded_output = embedding(input_indices)

# the output will be a tensor of shape (4, 6), where 4 is the number of inputs
# and 6 is the dimensionality of the embedding vector
print(embedded_output.shape)
print(embedded_output)


Embedding(80, 6)
torch.Size([4, 6])
tensor([[ 0.1431, -0.8183, -0.8503,  0.1864, -0.4267,  0.6304],
        [ 0.5105, -1.0574,  0.2474, -2.1840,  0.6837, -1.0494],
        [-0.8981,  0.7144,  0.3126,  0.3080,  1.0095,  0.3829],
        [-0.3597, -0.2427, -1.9480, -0.7136, -0.2164,  0.2738]],
       grad_fn=<EmbeddingBackward0>)


In [27]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(a @ b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [28]:
# type int64
int_64 = torch.randint(1, (3, 2)).float()

print(int_64)

# type float32
float_32 = torch.rand(2, 3)

print(float_32)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.2410, 0.1849, 0.2412],
        [0.0243, 0.4682, 0.3505]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [29]:
a = torch.rand(2, 3, 5)
x, y, z = a.shape
a = a.view(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
